--CONTEOS
SELECT COUNT(*) FROM Pais;
SELECT COUNT(*) FROM Idioma;
SELECT COUNT(*) FROM Categoria;
SELECT COUNT(*) FROM Actor;
SELECT COUNT(*) FROM Tienda;
SELECT COUNT(*) FROM Ciudad;
SELECT COUNT(*) FROM Cliente;
SELECT COUNT(*) FROM Empleado;
SELECT COUNT(*) FROM Pelicula;
SELECT COUNT(*) FROM Renta;
SELECT COUNT(*) FROM Pelicula_idioma;
SELECT COUNT(*) FROM Tienda_pelicula;
SELECT COUNT(*) FROM Pelicula_categoria;
SELECT COUNT(*) FROM Pelicula_actor;
