CREATE TABLE Temporal(
	nombre_cliente VARCHAR(40),
	correo_cliente VARCHAR(30),
	cliente_activo VARCHAR(2),
	fecha_creacion TIMESTAMP,
	tienda_preferida VARCHAR(40),
	direccion_cliente VARCHAR(70),
	codigo_postal_cliente VARCHAR(5),
	ciudad_cliente VARCHAR(30),
	pais_cliente VARCHAR(30),
	fecha_renta TIMESTAMP,
	fecha_retorno TIMESTAMP,
	monto_a_pagar DOUBLE PRECISION,
	fecha_pago TIMESTAMP,
	nombre_empleado VARCHAR(40),
	correo_empleado VARCHAR(30),
	empleado_activo VARCHAR(2),
	tienda_empleado VARCHAR(30),
	usuario_empleado VARCHAR(30),
	contrasena_empleado VARCHAR(50),
	direccion_empleado VARCHAR(40),
    codigo_postal_empleado VARCHAR(5),
	ciudad_empleado VARCHAR(30),
	pais_empleado VARCHAR(30),
    nombre_tienda VARCHAR(30),
    encargado_tienda VARCHAR(30),
    direccion_tienda VARCHAR(40),
    codigo_postal_tienda VARCHAR(5),
    ciudad_tienda VARCHAR(30),
    pais_tienda VARCHAR(30),
    tienda_pelicula VARCHAR(30),
    nombre_pelicula VARCHAR(30),
    descripcion_pelicula VARCHAR(200),
    ano_lanzamiento VARCHAR(4),
    dias_renta INT,
    costo_renta DOUBLE PRECISION,
    duracion INT,
    costo_por_dano DOUBLE PRECISION,
    clasificacion VARCHAR(5),
    lenguaje_pelicula VARCHAR(20),
    categoria_pelicula VARCHAR(20),
    actor_pelicula VARCHAR(30)
);

